codemate/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('create/',include('create.urls'))
]

create/urls.py
from django.conf.urls import url
from django.urls import path
from create import views

app_name='create'

urlpatterns=[
    url(r'^$', views.IndexView.as_view(), name="index"),

    url('paste/', views.CodeCreate.as_view(), name="detail"),

    path('result/<slug:slug>', views.result, name="result"),

    url('addObject/', views.addObject, name='addObject'),

    path('result/<slug:slug>/modify/', views.modify, name='modify'),

    path('result/<slug:slug>/delete/', views.DeleteObject.as_view(), name='delete'),
]

create/models.py
from django.db import models

# Create your models here.
class create_code(models.Model):
    slug=models.CharField(max_length=10)
    lang=models.CharField(max_length=100)
    content=models.CharField(max_length=10000)
    expire=models.CharField(max_length=100)

    def __str__(self):
        return self.content

create/views.py
from django.shortcuts import render
from django.views import generic
from create.models import create_code
from django.views.generic.edit import CreateView,DeleteView
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.

class IndexView(generic.ListView):
    template_name ='create/index.html'

    def get_queryset(self):
        return create_code.objects.all()


class CodeCreate(CreateView):
    model=create_code
    template_name = 'create/detail.html'
    fields=['slug','lang','content','expire']


def result(request, slug):
    object=create_code.objects.get(slug=slug)
    context={
        'object': object
    }
    return render(request,'create/result.html',context)

def addObject(request):
    print(request.method)
    content = request.POST['content']
    lang = request.POST['lang']
    slug = request.POST['slug']
    print(slug)
    print(content)
    expire = '1'
    newPaste = create_code(content=content, lang=lang, slug=slug, expire=expire)
    newPaste.save()
    rs = '/create/result/' + str(slug)
    return HttpResponseRedirect(rs);

def modify(request, slug):
    code = create_code.objects.get(slug=slug)
    code.content = request.POST['content']
    print(code.content)
    code.save()
    rs = '/create/result/' + str(slug)
    return redirect(rs);

class DeleteObject(DeleteView):
    model=create_code
    success_url=reverse_lazy('create:detail')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

create/templates/create/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Share-CodeMate</title>
    {%  load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/style.css' %}"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link href="https://fonts.googleapi.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js" type="text/javascript" charset="utf-8"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div  class="container-fluid">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>
            <a class="navbar-brand" href="{% url 'create:index' %} "><img src={% static 'create/images/capture.JPG' %} style="height:165%;border-radius:10px;"></a>


        <!--Items-->
        <ul class="nav navbar-nav navbar-right">

            <li class="">
                <a href="#"><span style="color:white">Sign Up</span></a>
            </li>
            <li class="">
                <a href="#"><span style="color:white">Login</span></a>
            </li>
            <li class="">
                <a href="#"<span style="color:white">Blog</span></a>
            </li>
        </ul>
        </div>
    </nav>



    <form action="{%  url 'create:addObject' %}" method="POST">
        {% csrf_token %}
       <div class="upper">


        <select id="id_lang" style="background-color: lightblue; border-radius: 30px; padding: 10px 24px; margin-left: 6%;" name="lang">
            {% include "create/lang.html" %}
        </select>
           <select id="id_theme" style="background-color: lightblue; border-radius: 30px; padding: 10px 24px; margin-left: 8%;position: absolute" name="theme">
            {% include "create/theme.html" %}
        </select>
        <input type="text" class='slug' name='slug' maxlength='10'  id='id_slug'  style=" text-align: center; background-color: lightblue; border-radius: 30px; padding: 8px 44px; margin-left: 35%; position: absolute;">

        <script>
            function makeid() {
              var text = "";
              var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

              for (var i = 0; i < 8; i++)
                text += possible.charAt(Math.floor(Math.random() * possible.length));

              return text;
            }


            document.getElementById("id_slug").value = makeid();
        </script>
    <input type="submit" value="Share Code" style="margin-left: 65%; background-color: lightblue; border-radius: 30px; padding: 10px 24px;position: absolute;"/><br><br>

       </div>


         <div id="editor" name="content" style="height: 600px; width: 1480px;margin-left: 17px;border-radius: 10px;"> </div>
             <textarea type='text' id='id_content' name='content' maxlength='1000000' style="display:none"></textarea>


             <script>
                var textarea = $('#id_content');
                var editor = ace.edit("editor");

                editor.setTheme("ace/theme/monokai");
                editor.getSession().setMode("ace/mode/javascript");

                editor.getSession().on('change', function () {
                textarea.val(editor.getSession().getValue());
                 });
                editor.focus()
                textarea.val(editor.getSession().getValue());
                $('#id_theme').on('change',function() {
                        editor.setTheme('ace/theme/'+$(this).val().toLowerCase());
                    });
                $('#id_lang').on('change',function() {
                        editor.setTheme('ace/mode/'+$(this).val().toLowerCase());
                    });
             </script>


    </form>

</body>
</html>

create/templates/create/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CodeMate</title>
    {%  load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/style.css' %}"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link href="https://fonts.googleapi.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar">
        <div  class="container-fluid">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>
            <a class="navbar-brand" href="{% url 'create:index' %} "><img src={% static 'create/images/capture.JPG' %} style="height:200%;border-radius:10px;"></a>


        <!--Items-->
        <ul class="nav navbar-nav navbar-right">
            <li class="ff">
                <a href="#"><span style="color:white">Sign Up</span></a>
            </li>
            <li class="">
                <a href="#"><span style="color:white">Login</span></a>
            </li>
            <li class="">
                <a href="#"<span style="color:white">Blog</span></a>
            </li>
        </ul>
        </div>
    </nav>


    <div class="main-text">
        <h1>Share Code in Real-time with Developers</h1>
    </div>
    <div class="main-text-tag">
        <h4>An online code editor.</h4>
    </div>
    <div class="main-btn">
        <button class="btn btn-info btn-lg" ><a href="{% url 'create:detail' %}">Share</a></button>
    </div>
    <div class="footer">
        <p>Created by <strong><u><a href="https://www.linkedin.com/in/siddharth-arya-353b0b62/">Siddharth Arya</a></u></strong>. For any feedback or queries <a href="mailto: aryasid98@gmail.com?subject=CodeMate%20Conversation"> mail</a> me.
        </p>
    </div>

</body>
</html>

create/templates/create/lang.html
{% block content %}

    <option>plain_text</option>
    <option>abap</option>
    <option>abc</option>
    <option>actionscript</option>
    <option>ada</option>
    <option>apache_conf</option>
    <option>applescript</option>
    <option>asciidoc</option>
    <option>asl</option>
    <option>assembly_x86</option>
    <option>autohotkey</option>
    <option>batchfile</option>
    <option>bro</option>
    <option>c9search</option>
    <option>cirru</option>
    <option>clojure</option>
    <option>cobol</option>
    <option>coffee</option>
    <option>coldfusion</option>
    <option>csharp</option>
    <option>csound_document</option>
    <option>csound_orchestra</option>
    <option>csound_score</option>
    <option>csp</option>
    <option>css</option>
    <option>curly</option>
    <option selected>c_cpp</option>
    <option>d</option>
    <option>dart</option>
    <option>diff</option>
    <option>django</option>
    <option>dockerfile</option>
    <option>dot</option>
    <option>drools</option>
    <option>edifact</option>
    <option>eiffel</option>
    <option>ejs</option>
    <option>elixir</option>
    <option>elm</option>
    <option>erlang</option>
    <option>forth</option>
    <option>fortran</option>
    <option>ftl</option>
    <option>gcode</option>
    <option>gherkin</option>
    <option>gitignore</option>
    <option>glsl</option>
    <option>gobstones</option>
    <option>golang</option>
    <option>graphqlschema</option>
    <option>groovy</option>
    <option>haml</option>
    <option>handlebars</option>
    <option>haskell</option>
    <option>haskell_cabal</option>
    <option>haxe</option>
    <option>hjson</option>
    <option>html</option>
    <option>html_elixir</option>
    <option>html_ruby</option>
    <option>ini</option>
    <option>io</option>
    <option>jack</option>
    <option>jade</option>
    <option>java</option>
    <option>javascript</option>
    <option>json</option>
    <option>jsoniq</option>
    <option>jsp</option>
    <option>jssm</option>
    <option>jsx</option>
    <option>julia</option>
    <option>kotlin</option>
    <option>latex</option>
    <option>less</option>
    <option>liquid</option>
    <option>lisp</option>
    <option>livescript</option>
    <option>logiql</option>
    <option>lsl</option>
    <option>lua</option>
    <option>luapage</option>
    <option>lucene</option>
    <option>makefile</option>
    <option>markdown</option>
    <option>mask</option>
    <option>matlab</option>
    <option>maze</option>
    <option>mel</option>
    <option>mixal</option>
    <option>mushcode</option>
    <option>mysql</option>
    <option>nix</option>
    <option>nsis</option>
    <option>objectivec</option>
    <option>ocaml</option>
    <option>pascal</option>
    <option>perl</option>
    <option>pgsql</option>
    <option>php</option>
    <option>pig</option>
    <option>plain_text</option>
    <option>powershell</option>
    <option>praat</option>
    <option>prolog</option>
    <option>properties</option>
    <option>protobuf</option>
    <option>python</option>
    <option>r</option>
    <option>razor</option>
    <option>rdoc</option>
    <option>red</option>
    <option>redshift</option>
    <option>rhtml</option>
    <option>rst</option>
    <option>ruby</option>
    <option>rust</option>
    <option>sass</option>
    <option>scad</option>
    <option>scala</option>
    <option>scheme</option>
    <option>scss</option>
    <option>sh</option>
    <option>sjs</option>
    <option>smarty</option>
    <option>snippets</option>
    <option>soy_template</option>
    <option>space</option>
    <option>sparql</option>
    <option>sql</option>
    <option>sqlserver</option>
    <option>stylus</option>
    <option>svg</option>
    <option>swift</option>
    <option>tcl</option>
    <option>tex</option>
    <option>text</option>
    <option>textile</option>
    <option>toml</option>
    <option>tsx</option>
    <option>turtle</option>
    <option>twig</option>
    <option>typescript</option>
    <option>vala</option>
    <option>vbscript</option>
    <option>velocity</option>
    <option>verilog</option>
    <option>vhdl</option>
    <option>wollok</option>
    <option>xml</option>
    <option>xquery</option>
    <option>yaml</option>


{% endblock %}

create/templates/create/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Final-CodeMate</title>
    {%  load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/style.css' %}"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link href="https://fonts.googleapi.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>


        <nav class="navbar navbar-inverse">
        <div  class="container-fluid">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>
            <a class="navbar-brand" href="{% url 'create:index' %} "><img src={% static 'create/images/capture.JPG' %} style="height:165%;border-radius:10px;"></a>


        <!--Items-->
        <ul class="nav navbar-nav navbar-right">

            <li class="">
                <a href="#"><span style="color:white">Sign Up</span></a>
            </li>
            <li class="">
                <a href="#"><span style="color:white">Login</span></a>
            </li>
            <li class="">
                <a href="#"<span style="color:white">Blog</span></a>
            </li>
        </ul>
        </div>
    </nav>
     <form action="{{ object.slug }}/modify/" method="POST">
        {% csrf_token %}
    <div class="upper">
        <input type="text" class="url"  id="url"  style="width: 450px; font-family: 'Buxton Sketch' ;font-size: 23px; background-color: lightslategray; border-radius: 30px; padding: 4px 30px;; margin-left: 6%;">
        <script>
            document.getElementById('url').value='http://127.0.0.1:8000/create/result/{{ object.slug }}'
        </script> &nbsp;
        <button onclick="myFunction()" style="border-radius: 50%; padding: 5px 10px;"><span class="glyphicon glyphicon-link" ></span></button>
        <script>
            function myFunction() {
              var copyText = document.getElementById("url");
              copyText.select();
              document.execCommand("copy");
            }
        </script>


        <input type="text" class="lang" id="lang" style="font-family: 'Buxton Sketch'; font-size: 23px; background-color: lightslategray; border-radius: 30px; padding: 3px 14px; margin-left: 6%; position: absolute;" name="lang">
        <script>
            document.getElementById('lang').value='{{ object.lang }}'
        </script>

        <input type="submit" value="Save" style="font-family: Pristina; font-size: 23px; background-color: lightslategray; border-radius: 30px; padding: 6px 15px; margin-left: 36%; position: absolute;"></input>

        <a href="{{ object.slug }}/delete/" style="font-family: Pristina; color: black; border: 2px solid;border-bottom-color: gray;border-top-color: white; border-right-color: gray; border-left-color: white;font-size: 23px; background-color: lightslategray; border-radius: 30px; padding: 6px 15px; margin-left: 45%; position: absolute;">Delete</a>
    </div>
<br>
        <div id="buffer" style="display: none">{{ object.content }}</div>
        <div id="editor" name="content" style="height: 600px; width: 1480px;margin-left: 17px;border-radius: 10px;"> </div>
             <textarea type='text' id='id_content' name='content' maxlength='1000000' style="display:none"></textarea>


             <script>
                var editor = ace.edit("editor");
                editor.getSession().setMode('ace/mode/c_cpp');
                editor.setTheme('ace/theme/monokai');
                editor.getSession().setMode('ace/mode/'+'{{ object.language }}'.toLowerCase())
                editor.getSession().setValue(document.getElementById('buffer').textContent);
                 $('#id_theme').on('change',function() {
                        editor.setTheme('ace/theme/'+$(this).val().toLowerCase());
                    });

                 var textarea=$('#id_content');
                 editor.getSession().on('change', function () {
                 textarea.val(editor.getSession().getValue());
                 });
                 textarea.val(editor.getSession().getValue());
             </script>
     </form>

</body>
</html>

create/templates/create/theme.html
{% block content %}

    <option>ambiance</option>
    <option>chaos</option>
    <option>chrome</option>
    <option>clouds</option>
    <option>clouds_midnight</option>
    <option>cobalt</option>
    <option>crimson_editor</option>
    <option>dawn</option>
    <option>dracula</option>
    <option>dreamweaver</option>
    <option>eclipse</option>
    <option>github</option>
    <option>gob</option>
    <option>gruvbox</option>
    <option>idle_fingers</option>
    <option>iplastic</option>
    <option>katzenmilch</option>
    <option>kr_theme</option>
    <option>kuroir</option>
    <option>merbivore</option>
    <option>merbivore_soft</option>
    <option selected>monokai</option>
    <option>mono_industrial</option>
    <option>pastel_on_dark</option>
    <option>solarized_dark</option>
    <option>solarized_light</option>
    <option>sqlserver</option>
    <option>terminal</option>
    <option>textmate</option>
    <option>tomorrow</option>
    <option>tomorrow_night</option>
    <option>tomorrow_night_blue</option>
    <option>tomorrow_night_bright</option>
    <option>tomorrow_night_eighties</option>
    <option>twilight</option>
    <option>vibrant_ink</option>
    <option>xcode</option>

{% endblock %}